apiVersion: v1
kind: Service
metadata:
  name: sentinel-manager
  namespace: sentinel 
spec:
  type: LoadBalancer
  ports:
    - port: 8099
      targetPort: 8099
  selector:
    sentinel: manager 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentinel-manager
  namespace: sentinel
spec:
  selector:
    matchLabels:
      sentinel: manager
  replicas: 1 
  template:
    metadata:
      labels:
        sentinel: manager
    spec:
      containers:
        - name: sentinel-manager
          image: jaehoon/sentinel-manager:latest
          ports:
            - containerPort: 8099
          env:
            - name: SENTINEL_DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: sentinel-configmap
                  key: db_host
            - name: SENTINEL_DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: sentinel-configmap
                  key: db_port
            - name: SENTINEL_DB_SCHEME
              valueFrom:
                configMapKeyRef:
                  name: sentinel-configmap
                  key: db_scheme
            - name: SENTINEL_DB_EXPORT_PATH
              valueFrom:
                configMapKeyRef:
                  name: sentinel-configmap
                  key: db_export_path
            - name: SENTINEL_DB_SERVER_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: sentinel-configmap
                  key: db_server_username
            - name: SENTINEL_DB_SERVER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sentinel-secret
                  key: db_server_password
            - name: SENTINEL_LOG_SEVERITY
              valueFrom:
                configMapKeyRef:
                  name: sentinel-configmap
                  key: log_severity
            - name: SENTINEL_LOG_SYSTEM_EVENT
              valueFrom:
                configMapKeyRef:
                  name: sentinel-configmap            
                  key: log_system_event
            - name: SENTINEL_LOG_VERBOSE
              valueFrom:
                configMapKeyRef:
                  name: sentinel-configmap 
                  key: log_verbose
            - name: SENTINEL_LOG_VERBOSELEVEL
              valueFrom:
                configMapKeyRef:
                  name: sentinel-configmap
                  key: log_verboselevel
            - name: SENTINEL_LOG_FILENAME
              valueFrom:
                configMapKeyRef:
                  name: sentinel-configmap
                  key: log_filename
            - name: SENTINEL_LOG_MAXSIZE
              valueFrom:
                configMapKeyRef:
                  name: sentinel-configmap
                  key: log_maxsize
            - name: SENTINEL_LOG_MAXAGE
              valueFrom:
                configMapKeyRef:
                  name: sentinel-configmap
                  key: log_maxage
            - name: SENTINEL_LOG_MAXBACKUPS
              valueFrom:
                configMapKeyRef:
                  name: sentinel-configmap
                  key: log_maxbackups
            - name: SENTINEL_LOG_COMPRESS
              valueFrom:
                configMapKeyRef:
                  name: sentinel-configmap
                  key: log_compress
